### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by BlueGoliath** [sasha0552/nvidia-pstate#2]
Hi,

This project clearly uses code that I had made available(and later made private) under the GPL -V3 license.

![2](https://github.com/sasha0552/nvidia-pstate/assets/10172435/0e3ebfe0-ea8f-421e-ba4a-4c8251756635)

Please fix the license.

**Comment by sasha0552** [comment]
Hello.
I don't know about your project and haven't used any of its code. I can't even compare the code to yours since your repo is private.
This project is not written in Java like yours, and I don't think the license can be applied to usage of NVIDIA's internal methods. There's no other way that doesn't utilize their API.
There are other projects that use the same API. For example, a simple search gives me [this](https://github.com/Demion/nvapioc/blob/63fc36c688231fa006951c72e99581e53105e604/Source/main.cpp#L388) project that uses it in [same](https://github.com/Demion/nvapioc/blob/63fc36c688231fa006951c72e99581e53105e604/Source/main.cpp#L739) way. That code has been added 6 years ago.
![image](https://github.com/sasha0552/nvidia-pstate/assets/45110640/5b9ab107-ebda-473a-8158-3d924c50c25c)
